import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import { DatePipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';

import { AnalysisApi } from '../../core/api/analysis.api';
import { AiAnalysisQuery, IssueAnalysisDto, Severity } from '../../core/models/analysis';
import { PagedResult } from '../../core/models/paged-result';
import { EmptyStateComponent } from '../../shared/components/empty-state.component';
import { PaginationComponent } from '../../shared/components/pagination.component';
import { SeverityPillComponent } from '../../shared/components/severity-pill.component';
import { SpinnerComponent } from '../../shared/components/spinner.component';
import { RelativeTimePipe } from '../../shared/pipes/relative-time.pipe';

const SEVERITIES: (Severity | 'All')[] = ['All', 'Critical', 'High', 'Medium', 'Low'];

@Component({
  selector: 'app-analysis-page',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    DatePipe,
    FormsModule,
    RouterLink,
    EmptyStateComponent,
    PaginationComponent,
    SeverityPillComponent,
    SpinnerComponent,
    RelativeTimePipe
  ],
  template: `
    <div class="shrink-0 mx-auto w-full max-w-7xl px-6 pt-8 pb-5">
      <div class="flex flex-wrap items-end justify-between gap-4">
        <div>
          <p class="text-[11px] font-semibold uppercase tracking-[0.2em] text-violet-300/80 mb-1.5">Intelligence</p>
          <h1 class="text-2xl font-bold tracking-tight text-white">AI Analyses</h1>
          <p class="mt-1 text-sm text-slate-400">Insights generated by the LogMind agent for grouped issues.</p>
        </div>

        <div class="flex flex-wrap items-center gap-1 rounded-lg border border-white/10 bg-black/20 p-1">
          @for (s of severities; track s) {
            <button type="button" (click)="setSeverity(s)" [class]="tabClass(s)">
              {{ s }}
            </button>
          }
        </div>
      </div>
    </div>

    <div class="flex-1 min-h-0 overflow-y-auto">
      <div class="mx-auto w-full max-w-7xl px-6 pb-8 space-y-6">
        @if (loading()) {
          <app-spinner />
        } @else if (rows().length === 0) {
          <div class="surface rounded-xl">
            <app-empty-state title="No analyses yet" description="The worker generates these once issues are grouped." />
          </div>
        } @else {
          <div class="grid gap-4 lg:grid-cols-2">
            @for (a of rows(); track a.id) {
              <article class="group relative overflow-hidden rounded-xl border border-white/[0.06] bg-white/[0.02] p-5 transition hover:border-violet-500/30">
                <span class="severity-stripe" [style.background]="severityColor(a.severity)"></span>

                <div class="pl-3 flex flex-col h-full">
                  <div class="flex items-start justify-between gap-3 mb-3">
                    <div class="space-y-1.5 min-w-0">
                      <app-severity-pill [severity]="a.severity" />
                      <p class="text-[10px] font-mono text-slate-600">
                        {{ a.createdAt | date:'medium' }} · {{ a.createdAt | relativeTime }}
                      </p>
                    </div>
                    <a [routerLink]="['/issues', a.issueId]"
                       class="inline-flex items-center gap-1 rounded-md border border-violet-500/20 bg-violet-500/5 px-2 py-1 text-[11px] font-medium text-violet-200 transition hover:bg-violet-500/15">
                      Open issue
                      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" class="h-3 w-3">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M9 5l7 7-7 7" />
                      </svg>
                    </a>
                  </div>

                  <h3 class="text-base font-semibold text-slate-100 group-hover:text-white">{{ a.summary }}</h3>

                  @if (a.rootCause) {
                    <p class="mt-3 text-sm text-slate-400 leading-relaxed">
                      <span class="text-slate-600 font-medium">Root cause: </span>{{ a.rootCause }}
                    </p>
                  }
                  @if (a.impact) {
                    <p class="mt-1 text-sm text-slate-400 leading-relaxed">
                      <span class="text-slate-600 font-medium">Impact: </span>{{ a.impact }}
                    </p>
                  }

                  @if (a.recommendations.length) {
                    <ul class="mt-3 space-y-1">
                      @for (rec of a.recommendations.slice(0, 3); track rec) {
                        <li class="flex gap-2 text-sm text-slate-300">
                          <span class="mt-0.5 text-violet-400 shrink-0">▸</span>
                          <span>{{ rec }}</span>
                        </li>
                      }
                    </ul>
                  }

                  @if (a.tags.length) {
                    <div class="mt-auto flex flex-wrap gap-1.5 pt-4">
                      @for (tag of a.tags; track tag) {
                        <span class="rounded-full bg-violet-500/10 px-2 py-0.5 text-[10px] text-violet-200 ring-1 ring-violet-500/30">
                          #{{ tag }}
                        </span>
                      }
                    </div>
                  }
                </div>
              </article>
            }
          </div>

          <div class="surface rounded-xl px-5 py-3">
            <app-pagination
              [page]="result()!.page"
              [pageSize]="result()!.pageSize"
              [totalCount]="result()!.totalCount"
              [totalPages]="result()!.totalPages"
              [hasNext]="result()!.hasNext"
              [hasPrevious]="result()!.hasPrevious"
              (pageChange)="goTo($event)" />
          </div>
        }
      </div>
    </div>
  `
})
export class AnalysisPage {
  private readonly api = inject(AnalysisApi);

  protected readonly severities = SEVERITIES;
  protected severity: Severity | 'All' = 'All';

  protected readonly result = signal<PagedResult<IssueAnalysisDto> | null>(null);
  protected readonly rows = computed(() => this.result()?.items ?? []);
  protected readonly loading = signal(true);

  private page = 1;
  private readonly pageSize = 20;

  constructor() { this.load(); }

  protected setSeverity(s: Severity | 'All') {
    this.severity = s;
    this.page = 1;
    this.load();
  }

  protected goTo(page: number) { this.page = page; this.load(); }

  protected tabClass(s: Severity | 'All'): string {
    const base = 'rounded-md px-3 py-1.5 text-xs font-medium transition';
    return this.severity === s
      ? `${base} bg-violet-500/15 text-violet-200 ring-1 ring-violet-500/30`
      : `${base} text-slate-400 hover:text-slate-200`;
  }

  protected severityColor(severity: string | null | undefined): string {
    switch ((severity || '').toLowerCase()) {
      case 'critical': return '#dc2626';
      case 'high': return '#fb923c';
      case 'medium': return '#f59e0b';
      case 'low': return '#10b981';
      default: return 'rgba(148, 163, 184, 0.4)';
    }
  }

  private load() {
    this.loading.set(true);
    const query: AiAnalysisQuery = {
      page: this.page,
      pageSize: this.pageSize,
      severity: this.severity === 'All' ? undefined : this.severity
    };
    this.api.search(query).subscribe({
      next: (res) => { this.result.set(res); this.loading.set(false); },
      error: () => this.loading.set(false)
    });
  }
}
